### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by guilhem** [ArthurHlt/go-eureka-client#1]
Hi @ArthurHlt 
Thank you for your project :)
Can you clarify license by pushing a `LICENSE` file?

**Comment by emilevauge** [comment]
I would love that too ;)

**Comment by ArthurHlt** [comment]
Sorry for my bad response time,

I have made a lot of change on the based code source but this is still not entirely mine and the original project didn't have any license so I was thinking what I should do.

I've put an MIT License so don't worry to use it. 

thank you for your contributions
